name: Ruby

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.1'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run Rubocop Linting
      run: bundle exec rubocop
